framework:
    messenger:
        transports:
            async:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                retry_strategy:
                    max_retries: 3
                    # milliseconds delay
                    delay: 1000

        routing:
            'App\Message\SmsNotification': async
            'App\Message\OtherSmsNotification': async
