framework:
    messenger:
        transports:
            async: "%env(MESSENGER_TRANSPORT_DSN)%"

        routing:
            'App\Message\SmsNotification': async
            'App\Message\OtherSmsNotification': async
