version: "3"

services:

  rurality:
    build: .
    image: moriorgames/symfony-sqs
    restart: unless-stopped
    container_name: symfony-sqs
    env_file:
      - .env
    volumes:
      - "./:/app"
    tty: true
